### PR TITLE
Fix #194, add some files to skip list

### LINKED ISSUE #194: New line (space?) at the end of text cause parser exception (found EOF when expected a new one value).

### PR DESCRIPTION
**Pull request by hatf0**
This brings the test coverage rate up to 73.33%.

### CODE REVIEW

File: source/mir/ion/deser/text/package.d [hunk 1]
```diff
@@ -234,7 +234,11 @@ private:
                 assert(typeHandlers[t.currentToken] !is null, "XXX: THIS SHOULD NEVER HAPPEN!");
                 typeHandlers[t.currentToken]();
                 return true;
+            case TokenEOF:
+                return false;
             default:
+                debug import std.stdio;
+                debug writefln("%s", t.currentToken);
```
Comment (9il) [inline source/mir/ion/deser/text/package.d:241]: Either remove it or 
```d
debug(ion_parser)
{
 ....
}
```
